# Generated by Django 5.2.7 on 2025-10-29 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Pelicula')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='peliculas/', verbose_name='Imagen')),
                ('restricciones', models.CharField(choices=[('APT', 'APT'), ('+14', '+14'), ('+18', '+18')], max_length=30, verbose_name='restricciones')),
            ],
        ),
    ]
