# Generated by Django 5.2.7 on 2025-10-31 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Genero')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='salas/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Pelicula')),
                ('sinopsis', models.TextField(blank=True, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='peliculas/', verbose_name='Imagen')),
                ('restriccion', models.CharField(choices=[('APT', 'APT'), ('+14', '+14'), ('+18', '+18')], max_length=30, verbose_name='restriccion')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duracion en minutos')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('generos', models.ManyToManyField(to='peliculas.genero', verbose_name='Genero')),
                ('salas', models.ManyToManyField(to='peliculas.sala', verbose_name='Sala')),
            ],
        ),
    ]
