# Generated by Django 5.2.7 on 2025-10-29 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del anuncio')),
                ('imagen', models.ImageField(upload_to='anuncios/', verbose_name='anuncios')),
                ('tipo', models.CharField(choices=[('SLIDER', 'Slider'), ('PROMOCION', 'Promocion')], max_length=50, verbose_name='tipo')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Enlace')),
                ('vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia')),
            ],
        ),
    ]
