# Generated by Django 5.2.7 on 2025-10-29 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen referencial')),
                ('categoria', models.CharField(choices=[('COMBO', 'Combo'), ('POPCORN', 'Popcorn'), ('BEBIDA', 'Bebida'), ('SNACK', 'Snack'), ('COLECCIONABLES', 'Coleccionables')], default='OTRO', max_length=50, verbose_name='Categoria')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
    ]
